import Link from "next/link";

export default function Hero() {
  return (
    <section className="relative pt-32 pb-32 px-6 overflow-hidden flex flex-col items-center justify-center min-h-[90vh]">
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-purple-900/20 via-[#0a0a0a] to-[#0a0a0a]">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[800px] h-[800px] rounded-full bg-purple-600/20 blur-[120px] mix-blend-screen animate-pulse delay-700" />
        <div className="absolute top-1/3 left-1/3 w-[600px] h-[600px] rounded-full bg-blue-600/20 blur-[120px] mix-blend-screen animate-pulse" />
        <div className="absolute top-1/2 right-1/4 w-[500px] h-[500px] rounded-full bg-emerald-600/10 blur-[100px] mix-blend-screen animate-pulse delay-1000" />
      </div>

      <div className="max-w-5xl mx-auto text-center z-10">
        <div className="inline-flex items-center gap-3 px-4 py-2 rounded-full border border-purple-500/30 bg-purple-500/10 text-purple-200 text-sm mb-8 shadow-[0_0_20px_rgba(168,85,247,0.2)] backdrop-blur-md transition-transform hover:scale-105 cursor-default">
          <span className="relative flex h-3 w-3">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-purple-400 opacity-75"></span>
            <span className="relative inline-flex rounded-full h-3 w-3 bg-purple-500"></span>
          </span>
          Generated by VibeCodex v3.0
        </div>

        <h1 className="text-6xl md:text-8xl font-extrabold tracking-tighter mb-8 leading-[1.1]">
          <span className="text-transparent bg-clip-text bg-gradient-to-br from-white via-white to-gray-400 drop-shadow-sm">Build faster,</span><br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-blue-400 to-emerald-400 drop-shadow-lg">
            ship sooner.
          </span>
        </h1>

        <p className="text-xl md:text-2xl text-gray-400 max-w-3xl mx-auto mb-12 font-light leading-relaxed">
          Your production-ready stack is live. Auth, AI and database — all seamlessly wired up and ready for scale.
        </p>

        <div className="flex flex-col sm:flex-row gap-5 justify-center items-center">
          <Link href="/dashboard" className="group relative px-8 py-4 rounded-2xl bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold text-lg transition-all hover:scale-105 hover:shadow-[0_0_40px_rgba(168,85,247,0.4)] overflow-hidden">
            <span className="absolute inset-0 bg-white/20 group-hover:translate-x-full transition-transform duration-500 ease-out -skew-x-12 -ml-4" />
            <span className="relative flex items-center gap-2">
              Go to Dashboard
              <svg className="w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
              </svg>
            </span>
          </Link>
          <Link href="/login" className="px-8 py-4 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-md text-gray-300 font-semibold text-lg hover:bg-white/10 hover:text-white transition-all hover:border-white/20">
            Sign In
          </Link>
        </div>
      </div>
    </section>
  );
}
