import { execa } from "execa";
import { retry } from "../utils.js";

export async function createAndPush(projectPath, name, username, token) {
  // 1. Init + commit
  await execa("git", ["init"], { cwd: projectPath });
  await execa("git", ["add", "."], { cwd: projectPath });
  await execa("git", ["commit", "-m", "🚀 Initial commit — generated by VibeCodex"], {
    cwd: projectPath,
  });

  // 2. Create private repo via GitHub API
  await retry(async () => {
    const res = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        Authorization: `token ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "vibecodex-cli",
      },
      body: JSON.stringify({
        name,
        private: true,
        auto_init: false,
        description: "Generated by VibeCodex 🚀",
      }),
    });

    if (!res.ok) {
      const err = await res.json();
      // Repo already exists = fine
      if (err.errors?.[0]?.message?.includes("already exists")) return;
      throw new Error(err.message || "GitHub API error");
    }
  });

  // 3. Push (token in URL, cleaned after push)
  const remoteWithToken = `https://${username}:${token}@github.com/${username}/${name}.git`;
  const cleanRemote = `https://github.com/${username}/${name}.git`;

  await execa("git", ["remote", "add", "origin", remoteWithToken], { cwd: projectPath });
  await execa("git", ["branch", "-M", "main"], { cwd: projectPath });
  await execa("git", ["push", "-u", "origin", "main"], {
    cwd: projectPath,
  });

  // 4. Remove token from stored remote
  await execa("git", ["remote", "set-url", "origin", cleanRemote], { cwd: projectPath });

  return cleanRemote;
}
